name: Deploy to Server

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-pip

      - name: Install packages
        run: pip install -r requirements_dev.txt

      - name: Tests
        run: pytest
